logging:
  level:
    bonjour.helloworld: debug
    org.springframework:
      security: debug

spring:
  custom:
    login: /api/token,POST
    authority: ROLE_USER
    jwt:
      ttl: 1h
      secret: secret!@#z?_43

server:
  error:
    include-stacktrace: never